// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDNySYgI0guWGG3KcNGyesLn9M4IYp9IEs',
    appId: '1:234212189980:web:733a60348e4515f1977cd9',
    messagingSenderId: '234212189980',
    projectId: 'iti-cours',
    authDomain: 'iti-cours.firebaseapp.com',
    storageBucket: 'iti-cours.appspot.com',
    measurementId: 'G-ZLQY9BLXW9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAr4xurf67i7LaKX41fkLOcn_uAkXxY6Tw',
    appId: '1:234212189980:android:09120147004af095977cd9',
    messagingSenderId: '234212189980',
    projectId: 'iti-cours',
    storageBucket: 'iti-cours.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyArsrCi4nZeL24as-MzS7V7q5vJLclF9so',
    appId: '1:234212189980:ios:c4b9d8c5a99e6ce7977cd9',
    messagingSenderId: '234212189980',
    projectId: 'iti-cours',
    storageBucket: 'iti-cours.appspot.com',
    iosClientId: '234212189980-el2tm2uiso0e5jeae5fhk7h10rhjqgai.apps.googleusercontent.com',
    iosBundleId: 'com.example.untitled',
  );
}
